### ISSUE TITLE
Reboot and Shutdown

### ISSUE THREAD

**Issue by xbgmsharp** [sphinx02/FireStarter#1]
Hi,

Thanks for this nice peace of software.
Would be nice to be able to reboot and shutdown the device from FireStarter.

**Comment by sphinx02** [comment]
Hi, should be possible, I check that and put it on my ToDo-List!

Thank you for the feedback :)

**Comment by sphinx02** [comment]
Hmmm looks not very good, to go to sleep amazon uses this function:
((PowerManager)InfosActivity.this.getActivity().getSystemService("power")).goToSleep(SystemClock.uptimeMillis());

which needs the permisson:
uses-permission android:name="android.permission.DEVICE_POWER" 

which is only accepted for system apps. Found no way to do this via ADB for now..

For reboot you can simply hold SELECT + PLAY buttons for about 4-5seconds. So no need to implement this into FireStarter (it would be possible via ADB REBOOT )..

**Comment by sphinx02** [comment]
Added possibility to reboot in v2.6 and still found no way to trigger sleep-mode without root-rights. Long-click home button and you are very near to put the FireTV into sleep!
