### ISSUE TITLE
Integrate parental control before uninstalling user app

### ISSUE THREAD

**Issue by junejosheeraz** [sphinx02/FireStarter#10]
Even if parental control is set Firestarter simply uninstall the app without promoting for my pin. This defeats the purpose if having in first place and I had to pay price when my baby uninstalled Kodi :(. I think we should be able to set PIN for firestarter only and it should prompt for it at least before uninstall It uninstalls

**Comment by djevertguzman** [comment]
I'd be more concerned about why your kid specifically uninstalled kodi.

**Comment by junejosheeraz** [comment]
They dont know what they are uninstalling... they just click...click...click...Closing as I have stopped using AppStarter!
