### ISSUE TITLE
Enhancement: HDMI CEC shortcuts for TV remotes

### ISSUE THREAD

**Issue by Dynalon** [sphinx02/FireStarter#11]
Hi,

I got a Sonia Bravia TV which has quite good support for HDMI CEC (which means I use my TVs remote for controlling the FireTv in Kodi & Netflix). The support without Firestarter is that good that I did not keep the original FireStarters Remote around anymore - all could be done with the TV remote.

Now It would be nice if FireStarter would allow to configure custom launch actions on double clicking the play/pause/fastforward/fastrewind buttons - because there is no Home button on Most TV remotes or they are not part of the CEC passthrough.

The buttons working for Sony Bravia TVs:
- Up/down/left/right (works for navigating through Amazon Launcher, Netflix, Kodi)
- Play & Pause (these are two different buttons on the TV remote and work each on their own in netflix and Kodi)
- Fastforward & Rewind (work the same way as original FireTVs remote)
- Color buttons (green, red, yellow, blue) - These are not used by FireTV at all but I used a RasperryPi with Kodi on the same TV and I could map shortcuts to the color buttons of the TVs remote and they were received so I guess they are passed through the HDMI CEC.

If you could add support for catching double tap events and allow launching of custom apps that would be great. If its possible to map the color buttons, that be even more great (because you normally don't use them). People could use their TV remotes to start Netflix or Kodi for example by double tapping the Rewind or Forward button. At the moment custom launch actions are limited to the FireTV remote only.

Thanks for considering and keep up the good work! I could test this feature before a release if you don't have a CEC-enable TV.

**Comment by Dynalon** [comment]
I took a look at the sourcecode (I am a professional programmer but not so familiar with Java/Android) and could see you are watching the logcat outputs to determin button press events. I could connect to my FireTV and did an `adb logcat` to obtain the following outputs after pressing the buttons on the remote:

## Media control

### Play button

```
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x44, InMsg.operand[0]=0x44
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x45, InMsg.operand[0]=0x0
```

### Pause button (different button on remote, different output)

```
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x44, InMsg.operand[0]=0x46
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x45, InMsg.operand[0]=0x0
```

### Rewind button

```
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x44, InMsg.operand[0]=0x48
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x45, InMsg.operand[0]=0x0
```

### Forward button

```
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x44, InMsg.operand[0]=0x49
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x45, InMsg.operand[0]=0x0
```

### Stop button

```
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x44, InMsg.operand[0]=0x45
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x45, InMsg.operand[0]=0x0
```

## Navigation

### Left

```
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x44, InMsg.operand[0]=0x3
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x45, InMsg.operand[0]=0x0
```

### Right

```
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x44, InMsg.operand[0]=0x4
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x45, InMsg.operand[0]=0x0
```

### Up

```
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x44, InMsg.operand[0]=0x1
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x45, InMsg.operand[0]=0x0
```

### Down

```
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x44, InMsg.operand[0]=0x2
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x45, InMsg.operand[0]=0x0
```

### OK button (centered in navigation cross/circle)

```
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x44, InMsg.operand[0]=0x0
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x45, InMsg.operand[0]=0x0
```

### Return button

```
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x44, InMsg.operand[0]=0xd
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x45, InMsg.operand[0]=0x0
```

### Red button

```
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x44, InMsg.operand[0]=0x72
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x45, InMsg.operand[0]=0x0
```

### Green button

```
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x44, InMsg.operand[0]=0x73
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x45, InMsg.operand[0]=0x0
```

### Yellow button

```
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x44, InMsg.operand[0]=0x74
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x45, InMsg.operand[0]=0x0
```

### Blue button

```
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x44, InMsg.operand[0]=0x71
I/CECDAEMON(  336): CECProcessCmds: CEC Keyevents commands: opcode=0x45, InMsg.operand[0]=0x0
```

To me it seems the second event indicates a key up event, but does not indicate which key. The `0x44` seems to indicate a CEC keydown event, and the operand carries the information which button was pressed.

The remote i used to obtain the values:
![Sonia Bravia TV Remote](https://dl.dropbox.com/s/wvkrwecrq2y425w/braviaremote.jpg)

**Comment by Dynalon** [comment]
I found the [CEC spec](https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0CCEQFjAAahUKEwi_4Z2QqYbIAhXICBoKHVtmCso&url=https%3A%2F%2Fxtreamerdev.googlecode.com%2Ffiles%2FCEC_Specs.pdf&usg=AFQjCNE62Z43nIl4vYa9hLqpUgb-bmWZXA&sig2=IP_XNZw0ePioBbfhLFSdmA), 0x44 is indeed the opcode and the intereting field is the "ui command"- the spec has a full list of those commands (page 95 of 97):

![cecopcodes](https://dl.dropbox.com/s/5z0f9by2q428px2/cecuicodes.png)

In addition, I found out that the TV also emits messages when the Input source is switched (for example to a gaming console hdmi input), or if i switch to teresstric TV (pressing a number). Also messages are emmited when the TV is powered down. Parsing these message would allow very nice additions to FireStarter, like pausing playback (simulation a pause button press?) and/or putting the FireTV to sleep afterwards.

**Comment by sphinx02** [comment]
Hi,
sounds very interesting and useful! I will definetly think about some CEC support, but first I will wait for the final FireOS 5 update to be sure the whole adb-parse-mechanism is still working on the new FireOS.

Thank you for your detailed analyses, this will definetly help alot when it comes to an implementation!

**Comment by RedAnt79** [comment]
For the record, I was not able to see those log statements with my FireTV Stick using Fire OS 5.0.3 (532008220) with a 2011 Sony Bravia KDL-40HX755
With Fire OS 3 I was able to just use the TV remote, but with Fire OS 5 I need the fire remote for two reasons: Home Button is not mapped to anything on the Bravia remote (before I started Kodi using Llama) and if your Pin contains a 0 or a 5 you are out of luck (center button is mapped to bravia remote, but not during input of pin).

**Comment by gruselglatz** [comment]
Is there some Progress for Supporting HDMI-CEC again on Fire-TV-Stick?

**Comment by cwilko** [comment]
+1 would really like to see this happen!

**Comment by Dynalon** [comment]
I just hat time to test again with an up-2-date FireTV on FireOS5 and the CEC signals are still captured. However, the log output format has changed.

I could obtain the CEC output via adb by disabling FireStarters adb mode and rebooting the FireTV, then connecting to my FireTV:

```
adb kill-server
adb start-server
adb connect 192.168.1.11  # the ip of my FireTV
adb logcat qdhdmi_cec *:S  #will show keypresses on my TV remote in logcat, filtering unwanted outputs
```

An example output of pressing the `red` button on the remote:

```
D/qdhdmi_cec(  789): cec_loop: Triggered
D/qdhdmi_cec(  789): cec_loop: CEC frame towards framework (len=20)
D/qdhdmi_cec(  789): cec_receive_message: Message from driver: 00:04:44:72:00:00:00:00:00:00:00:00:00:00:00:00:00:00:03:00
D/qdhdmi_cec(  789): cec_receive_message: Message to framework: 44:72
D/qdhdmi_cec(  789): cec_loop: Triggered
D/qdhdmi_cec(  789): cec_loop: CEC frame towards framework (len=20)
D/qdhdmi_cec(  789): cec_receive_message: Message from driver: 00:04:45:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:02:00
D/qdhdmi_cec(  789): cec_receive_message: Message to framework: 45
```

The important part is the line `Message to framework: 44:72` that contains the CEC key encoded after the colon. In the table I posted earlier, `0x72` is the keycode for `red`. I can also confirm the message will be `44:73` for green, and so on.

I could re-post all possible outputs for each keypress if anyone is interested on putting this into FireStarter. I'd love to have the color-keys on the remote be app-shortcuts that launch various apps (i.e. german mediatheken apps, different for every color). And as already mentioned, at least my TV sends CEC signals when switching the TV input, so this could also be used to send the FireTV to sleep.

**Comment by Novo** [comment]
any update about implementation?

**Comment by rbreaves** [comment]
Further info.

On FireTV OS 5
"/system/etc/permissions/android.hardware.hdmi.cec.xml"
```
<permissions>
    <feature name="android.hardware.hdmi.cec" />
</permissions>
```

https://source.android.com/devices/tv/hdmi-cec

```
root@tank:/sys/class # dumpsys hdmi_control
mHdmiControlEnabled: true
mProhibitMode: false
mCecController:
  HdmiCecLocalDevice #0:
    mDeviceType: 4
    mAddress: 4
    mPreferredAddress: 4
    mDeviceInfo: CEC: logical_address: 0x04 device_type: 4 vendor_id: 3303 display_name: AFTT power_status: -1 physical_address: 0x1000 port_id: 1
    mActiveSource: logical_address: invalid, physical_address: invalid
    mActiveRoutingPath: 0x0000
    mIsActiveSource: true
mMhlController:
mPortInfo:
  - port_id: 1, address: 0x1000, cec: true, arc: false, mhl: false
mPowerStatus: 0
```

This is also interesting but only applicable to Android TV boxes..
https://android.developreference.com/article/12924728/HDMI+CEC+on+android

```
So I decided to go directly through OS level and it worked. Specifically in this dongle, you have at /sys/class/cec two important files:
. cmd (to send cec commands)
e.g. (as root # android shell )
#turn on tv
echo 0x40 0x04 > /sys/class/cec/cmd
#change input source to HDMI 1
echo 0x4F 0x82 0x10 0x00 > /sys/class/cec/cmd
#change input source to HDMI 1
echo 0x4F 0x82 0x10 0x00 > /sys/class/cec/cmd
. dump_reg ( to read output of cec)
Use this site to check codes for other commands
```

Hoping for something similar to their dump_reg.. I ran this but found nothing.

```
root@tank:/sys/class # find /sys/ -name *dump*
/sys/fs/selinux/class/debuggerd/perms/dump_backtrace
/sys/fs/selinux/class/debuggerd/perms/dump_tombstone
/sys/bus/platform/devices/dbg_reg_dump.0
/sys/ptp/ptp_dump
/sys/devices/platform/dbg_reg_dump.0
/sys/kernel/debug/mali/state_dump
/sys/kernel/debug/tracing/events/cfg80211/rdev_dump_station
/sys/kernel/debug/tracing/events/cfg80211/rdev_dump_mpath
/sys/kernel/debug/tracing/events/cfg80211/rdev_testmode_dump
/sys/kernel/debug/tracing/events/cfg80211/rdev_dump_survey
/sys/module/printk/parameters/always_kmsg_dump
/sys/module/mt_sleep/parameters/slp_dump_gpio
/sys/module/mt_sleep/parameters/slp_dump_regs
```

More useful info
logcat -v tag | grep -e "^..hdmi*"
```
D/hdmi_cec: [HWCEC] ucecevents: hdmi CEC_TX_STATUS callback...
I/hdmi_cec: [HWCEC] get_txstatus,  cond=0 curcode= 0x47
I/hdmi_cec: [HWCEC] send_message end, opcode(mCurrCode): 0x47, mResult:0,DurMs:439 ms
D/hdmi_u_event: handle hdmi uevents: s=change@/devices/virtual/switch/cec_hdmi, len=162
D/hdmi_u_event: change_hdmi=0, change_hdmi_res=0
D/hdmi_u_event: handle hdmi uevents: s=change@/devices/virtual/switch/cec_hdmi, len=160
I/hdmi_cec: [HWCEC] send_message init:4, dest:0, opcode: 0x47, size:13, body[0]=0x46
```

It appears like we're dealing with hdmi_cec in these locations
```
/sys/devices/virtual/switch/cec_hdmi
/sys/class/switch/cec_hdmi
```

**Comment by rbreaves** [comment]
Update: If someone would like to compile this for me to run on Android 5.1 then I would appreciate it. I might be able to pull down the bytes the original controller is sending and convert that to what is needed faster than expected.

https://github.com/dhylands/ueventmon

One negative challenge will be that any time the firetv remote goes to sleep and comes back it's input position will be lost and will increment the number.. so it'll continually go up. A script of some kind will need to keep track of it... but we might also need to figure out if there is a way to prevent or keep the remote from going to sleep. If the firetv emits that to the controller then we need to figure out how to prevent that from occurring or how to stop the device from disappearing on the firetv side.

---------------------------------

I sorta know how to do it.. but I need some help on figuring it out for good. Only Amazon's remotes have this feature, but we can bring it to 3rd party controllers if we fake it on rooted devices.. This is how one would FAKE it to make it happen.

And this is the key line on how I know this will work once we have the string formatted correctly to issue the volume up/down or power command.

```
09-28 04:14:33.940 I/Kernel  (10080): [ 8744.952720].(2)[10080:sh]input input12: uevent: unknown action-strin
```

This is how you figure out which input device is your original firetv remote (no idea if this works with firetv remotes that don't really have a real volume button or not, I suspect as long as you have synced a volume and power capable controller once to your firetv the hdmi-cec service will be activated and it is not only tied to one controller type (outside of the keylayout definitions. This method I doubt will care though.)

Step 1) Figure out your input location
```
# ls /sys/class/input/
event0
event1
event2
event3
event4
event5
event6
event7
input0
input1
input12
input5
input6
input7
input8
input9
```

Ignore all of the event paths, but do check the name values by cat'ing them out.

example
```
# cat /sys/class/input/input12/name
Amazon Fire TV Remote
```


Now that you have that we need to figure out the properly formatted string or syntax to send into uevent of the controllers.

```
root@tank:/sys/class/input/input12 # echo 23 > ./uevent
root@tank:/sys/class/input/input12 # logcat -v time
--------- beginning of amazon_main
09-28 04:14:30.908 I/JmDNSImpl(10924): updateRecord() name=cc:44:63:b6:dd:01@fe80::ce44:63ff:feb6:dd01 typeSubType=_apple-mobdev2._tcp.local. op=Remove #listeners=0
--------- beginning of kernel
09-28 04:14:33.940 I/Kernel  (10080): [ 8744.952720].(2)[10080:sh]input input12: uevent: unknown action-string
09-28 04:14:34.500 I/Kernel  (    0): [ 8745.509156]-(0)[0:swapper/0][printk_delayed:start]
09-28 04:14:34.500 I/Kernel  (    0): [ 8745.509189]-(0)[0:swapper/0][WDK], local_bit:0x8, cpu:0,RT[8745499176504]
09-28 04:14:34.500 I/Kernel  (    0): [ 8745.509189][WDK], local_bit:0x9, cpu:0, check bit0x:f,RT[8745499185966]
09-28 04:14:34.500 I/Kernel  (    0): [ 8745.509189][thread:60][RT:8745499193043] 2020-09-28 08:14:34.496154 UTC; android time 2020-09-28 03:14:34.496154
```

The original controller looks like this when pressing volume up against an hdmi-cec tv successfully
```
09-28 04:31:28.861 I/OZ-DCS:KeyPressReceiver( 1477): Received keyCode: KEYCODE_VOLUME_UP
09-28 04:31:28.861 I/OZ-DCS:KeyPressReceiver( 1477): Remote button pressed. keyCode: 24, keyEvent: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_VOLUME_UP, scanCode=115, metaState=0, flags=0x8, repeatCount=0, eventTime=9759841, downTime=9759841, deviceId=13, source=0x301 }
09-28 04:31:28.862 I/OZ-DCS:KeyPressReceiver( 1477): Received keyCode: KEYCODE_VOLUME_UP
09-28 04:31:28.862 I/OZ-DCS:KeyPressReceiver( 1477): Remote button pressed. keyCode: 24, keyEvent: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_VOLUME_UP, scanCode=115, metaState=0, flags=0x8, repeatCount=0, eventTime=9759842, downTime=9759841, deviceId=13, source=0x301 }
```

I might be seeing what needs to be sent more or less.. monitoring the kernel can lead to success.

```
logcat -v tag | grep -e "^..Kernel*"
```
The bytes to be sent need to relate to the entire payload I think..
```
Remote button pressed. keyCode: 24, keyEvent: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_VOLUME_UP, scanCode=115, metaState=0, flags=0x8, repeatCount=0, eventTime=9759841, downTime=9759841, deviceId=13, source=0x301 }
```

/sys/class/input/input13 # echo -e '\x01\x0D' > ./uevent
otherwise you get this
```
I/Kernel  : [12731.955841].(2)[10080:sh]input input13: uevent: unknown action-string
I/Kernel  : [12733.857110].(2)[10080:sh]input input13: uevent: unknown action-string
```

Need the proper bytes for the following and I assume in hex.
ACTION_DOWN
KEYCODE_VOLUME_UP
115
0x8
0
9759841
9759841
13
0x301

**Comment by rbreaves** [comment]
Sorry if it feels like I’m spamming this thread. Found a good guide & code example of injecting key presses. Assuming a more direct approach/ API interfaces are not found in the short term.

https://github.com/radhoo/android-event-injector


cat /sys/class/input/input12/uevent
```
PRODUCT=3/171/413/0
NAME="Amazon Fire TV Remote"
PHYS=""
UNIQ="7C:D5:66:83:4B:09"
PROP=0
EV=100013
KEY=3007f 0 0 0 0 483ffff 17aff32d bf544446 0 0 1 130f93 8b17c007 ffff7bfa d9415fff febeffdf ffefffff ffffffff fffffffe
MSC=10
MODALIAS=input:b0003v0171p0413e0000-e0,1,4,14,k71,72,73,74,75,77,79,7A,7B,7C,7D,7E,7F,80,81,82,83,84,85,86,87,88,89,8A,8B,8C,8E,90,96,98,9B,9C,9E,9F,A1,A3,A4,A5,A6,A7,A8,A9,AB,AC,AD,AE,B0,B1,B2,B3,B4,B5,B6,B7,B8,B9,BA,BB,BC,BD,BE,BF,C0,C1,C2,CE,CF,D0,D1,D2,D4,D8,D9,DB,DF,E0,E1,E4,E7,E8,E9,EA,EB,F0,F1,F4,100,161,162,166,16A,16E,172,174,176,178,179,17A,17B,17C,17D,17F,180,182,183,185,188,189,18C,18D,18E,18F,190,191,192,193,195,197,198,199,19A,19C,1A0,1A1,1A2,1A3,1A4,1A5,1A6,1A7,1A8,1A9,1AA,1AB,1AC,1AD,1AE,1AF,1B0,1B1,1B7,1BA,240,241,242,243,244,245,246,250,251,ram4,lsfw
```

I guess since the OP is no longer interested and closed this thread I will later re-open it when I have done more research and work on this. I just hoping to make this a collaborative effort, hadn't noticed this thread has been open for 5 years lol. I imagine the OP just doesn't care anymore.

**Comment by rbreaves** [comment]
2nd Update: As a work around to communicating over hdmi-cec.

If you own smart TV devices that connect with their own ip then it may also be possible to just re-route controlling them more directy.

Roku Ex.
```
curl -d "" http://192.168.1.169:8060/keypress/PowerOff
curl -d "" http://192.168.1.169:8060/keypress/VolumeDown
curl -d "" http://192.168.1.169:8060/keypress/VolumeUp
curl -d "" http://192.168.1.169:8060/keypress/VolumeMute
```
Others like LG's webos tv also have the ability, but you may need to setup a raspberry pi or another device to run a package to make it easier to communicate with. Once you do these things then you can use an app like Button Mapper from the google play store that can redirect button presses to what you want.

--------------------------
Update: After more testing I am realizing that I am in fact able to make successful inputs and that my volume issue is actually from the fact that the remote is really using IR to control my volume and not hdmi-cec. What I thought was a fallback is actually the primary. So I guess I am sort of back at ground zero on all this unless I find that one of the /dev/input devices is the actual hdmi-cec device.

------------------------
Found a way to capture what I needed and play it back, and even though the kernel sees that data as it should it also knows it is not coming from the original device somehow so it is promptly ignored. Will either need to disable the security check or try and capture the replay the data going into hdmi_cec directly, assuming the same security checks do not apply.

https://github.com/Cartucho/android-touch-record-replay
https://qatesttech.wordpress.com/2012/06/21/turning-the-output-from-getevent-into-something-something-that-can-be-used/

Volume down using getevent & in hex
```
[   18099.082628] 0004 0004 000c00ea

[   18099.082628] 0001 0072 00000001

[   18099.082628] 0000 0000 00000000

[   18099.083150] 0004 0004 000c00ea

[   18099.083150] 0001 0072 00000000

[   18099.083150] 0000 0000 00000000
```

Volume down converted to decimal and thrown back in using sendevent
```
adb shell sendevent /dev/input/event7 4 4 786666
adb shell sendevent /dev/input/event7 1 114 1
adb shell sendevent /dev/input/event7 0 0 0
adb shell sendevent /dev/input/event7 4 4 786666
adb shell sendevent /dev/input/event7 1 114 0
adb shell sendevent /dev/input/event7 0 0 0

# or if logged in, can also be added to a sh script

logcat -c
sendevent /dev/input/event7 4 4 786666
sendevent /dev/input/event7 1 114 1
sendevent /dev/input/event7 0 0 0
sendevent /dev/input/event7 4 4 786666
sendevent /dev/input/event7 1 114 0
sendevent /dev/input/event7 0 0 0
logcat 
```
