### ISSUE TITLE
Fire TV box 4K

### ISSUE THREAD

**Issue by delaware1999** [sphinx02/FireStarter#14]
Hello I just got today my German Fire TV 4K Box. I did install fire starter but I doesnt work like it should !
is there a new update comming ? Is it working with the new 4K box ?

**Comment by sphinx02** [comment]
Disable & enable ADB after reboot is not anymore needed. Still no parallel ADB connections possible. Jumpback Watchdog problems are fixed, you can safely set it back to default of 5000ms.

see https://github.com/sphinx02/FireStarter/releases/tag/v3.0
