### ISSUE TITLE
FireTV 4K ... how to donate one?!

### ISSUE THREAD

**Issue by assarbad** [sphinx02/FireStarter#15]
@sphinx02 would donating a FireTV of the new version help to speed up a fix for the issue?

I am not yet acquainted enough with Android development in general to be of any use so don't expect pull requests from me. But I'd definitely send you a FireTV if you're interested.

No strings attached. Don't want to be mentioned anywhere either. Just out of the egotistical motive of being able again to use this on the new version ;)

Find the contact page on my website and shoot me a message. Easiest without disclosing your own address to me would be to send me a private Amazon.de wishlist link with the FireTV on the list (at least it used to work this way in the past).

**Comment by jdrobert** [comment]
I would be happy to contribute to this as well.

**Comment by sphinx02** [comment]
In general it is always better to have the real target device to check if things do really work. This also speeds up development as I am then able to test all three platforms at my home (FireTV, FireTV-Stick and FireTV2). For now I started development for FireOS5 with the (updated) Developer Preview version of FireOS5 on my FireTV-Stick. I hope to achieve progress without a FireTV2. At the moment I am not willing to buy an own FireTV2 as I already have a FireTV and FireTV-Stick. Sadly there was no half-price-offer when ordering the FireTV2 on the first day :(

@assarbad 
Thank you very much for your offer, I sent you an e-mail to the address mentioned on your website. It's really ok if you decide not to donate a whole FireTV2.

@jdrobert 
Perhaps you can contact assarbad in terms of the FireTV2 donation.

**Comment by assarbad** [comment]
I'm sure there will be a hardware update some other time, so if @jdrobert wants to donate he could do it then. No need to chip in this time, it's already been paid for :-)

@sphinx02 you should have it by tomorrow.
