### ISSUE TITLE
amazon fire tv 2

### ISSUE THREAD

**Issue by gbrooke** [sphinx02/FireStarter#16]
If u are the proud owner of the new Amazon firetv 4K box and you are having problems with firestarter after installing it ..
Reboot box - developers options - ADB debugging turn it off then back on then launch firestarter and it will work perfectly
Hope this helps

**Comment by Haunavi** [comment]
Hi
Do I have to reboot the device every time I turn on?
Thanks

**Comment by gbrooke** [comment]
Just put mine to sleep and woke it up and firestarter was fine, so seems to
be just that first time

**Comment by Haunavi** [comment]
Is kodi flashing when u open kodi? Mine flashing 4 or 5 time when I open it? How can I stop that?
Thanks

**Comment by gbrooke** [comment]
Haven't had that problem, my kodi opens fine....I'm on 15.2 RC3

**Comment by imagica71** [comment]
@Haunavi 
set Jump Back Watchdog Timer to 0 (thx to @malone7201), then kodi won't flash anymore.

**Comment by vip32** [comment]
re-enabling adb does not solve the issue on my aftv2

**Comment by sphinx02** [comment]
Disable & enable ADB after reboot is not anymore needed. Still no parallel ADB connections possible. Jumpback Watchdog problems are fixed, you can safely set it back to default of 5000ms.

see https://github.com/sphinx02/FireStarter/releases/tag/v3.0
