### ISSUE TITLE
3.0 working good.

### ISSUE THREAD

**Issue by LaffinAtcha** [sphinx02/FireStarter#17]
@sphinx02 I just put 3.0 on my AFTV2 and it works exactly as described. Thank you so much!

**Comment by delaware1999** [comment]
@sphinx02 Did you use it on FIRE TV BOX 2  4K version ?

**Comment by sphinx02** [comment]
Nope as mentioned in the changelog, I still have no "FIRE TV BOX 2 4K", but there is one on the way to me. Next update will be tested on the FireTV2.

see https://github.com/sphinx02/FireStarter/releases/tag/v3.0

**Comment by ways2web** [comment]
http://www.golem.de/news/fire-starter-3-0-ausprobiert-fire-tv-app-starter-an-fire-os-5-angepasst-1510-116802.html

**Comment by sphinx02** [comment]
Never been a real issue..
