### ISSUE TITLE
Launching Kodi at boot?

### ISSUE THREAD

**Issue by D-an-W** [sphinx02/FireStarter#19]
Hi folks, just tried FireStarter v3.0 for the first time on my Fire TV and Fire TV Stick (Both running latest v5 firmware).

If I set it to launch Kodi (v15.2 RC3) on boot of the Fire TV I am left with a black screen until I single press any button on the remote. Once I have done this, Kodi launches normally.

If I set it to launch Kodi (v15.2 RC3) on boot of the Fire TV Stick again, I am left with a black screen but if I do the single button press nothing happens but with a second button press it goes back to the Fire TV home screen.

I was trying to get it setup as follows:

Single Home Button Press = Fire TV Home
Double Home Button Press = FireStarter
Auto launch at boot = Kodi

Could this be an issue with FireStarter or is it possibly a Kodi related problem?

**Comment by LaffinAtcha** [comment]
I have mine set up like this:
Start up app Fire Tv
Single click None
Double click Kodi
Works flawlessly for me.

**Comment by sphinx02** [comment]
Just checked it and for me it works. In general it should be possible to launch every app at startup. Perhaps this is a specific problem with your FireTV and Kodi v15.2 RC3 combination. Hard to help if I can not reproduce the behaviour..

**Comment by D-an-W** [comment]
Thanks for testing it, FireStarter and Fire TV Settings work from boot ok so it could well be a Kodi issue.

What version of Kodi did you test with, the same as me?

**Comment by sphinx02** [comment]
I am still using Kodi 14.2

**Comment by D-an-W** [comment]
Now working well with new version.
