### ISSUE TITLE
display timeout

### ISSUE THREAD

**Issue by ways2web** [sphinx02/FireStarter#2]
ich habe festgesteltt, dass nach der frischen installation alles super läuft.
Nach einer nacht und dem erwecken aus dem ruhemodus (oder auch neustart) schaltet sich der bildschirm sehr schnell dunkel. Das passiert nach ca 5-10 sek., wenn sich keine aktivität auf der tut.

Sobald ich auf der fernbedienung eine taste drücke ist das bild sofort wieder da.

zwei mal den stick zurückgesetzt und firestarter frisch aufgesetzt. Jedesmal das gleiche problem.
was könnte das sein?

Ohne Firestarter macht der Stick das nicht.

**Comment by sphinx02** [comment]
Please stay in english on GitHub. On android-hilfe.de we can discuss in german.

As I already answered your question on android-hilfe.de, if you havent used the settings in the system-tab, it is nearly impossible that FireStarter is the reason for your behaviour. If you have played around with the sleep-settings in the system-tab, it can be that you have changed the sleep-timeout. This is a system-setting which stays even if you have deinstalled FireStarter! So be careful with these settings, the default sleep timeout of amazon is 30 minutes!

Let me know if you can fix your problems by checking / changing the sleep timeout..
Best regards
Lukas

**Comment by ways2web** [comment]
:+1:

**Comment by sphinx02** [comment]
Problem is further discussed on android-hilfe.de
