### ISSUE TITLE
Question: Possible to Setup via adb

### ISSUE THREAD

**Issue by Shinoby1992** [sphinx02/FireStarter#24]
Hello, greets from germany ;P 
Back to Topic 

I want to configurate/setup firestarter after install via adb
-> home button Kodi
-> first app start Kodi
-> Double button FireHome

Is this possible, if yes? where is the config file i have to push, and of course where i have to push it to?
or is there a way to do this via adb commands?

**Comment by sphinx02** [comment]
Check this post, I guess you have to customize it a little bit for the current version, but here you can get an idea how to do this:
http://forum.xda-developers.com/showpost.php?p=61803807&postcount=110

**Comment by Shinoby1992** [comment]
it works thank you :-)
