### ISSUE TITLE
App starting behavior 

### ISSUE THREAD

**Issue by imagica71** [sphinx02/FireStarter#26]
Hello,
if i launch an app (Magine) from the Fire TV home screen, it starts in landscape Mode but if i start it from firestarter, it starts in portrait mode. On the other hand, if i start it from the context menu from within firestarter (where you can deinstall, clear cache etc.) it starts also in landscape mode.

Whats the difference in the start procedure? 

Thanks Marco

anyway i don't know if this is an issue from firestarter :-)

**Comment by sphinx02** [comment]
Hi Marco,
this is a known bug / behaviour which is only true for this specific app: Magine. I havent yet investigated in checking why Magine behaves different when started from FireStarter..

**Comment by sphinx02** [comment]
Fixed in https://github.com/sphinx02/FireStarter/releases/tag/v3.2.2
