### ISSUE TITLE
Tablo launches into incorrect UI from Firestarter

### ISSUE THREAD

**Issue by riseagainstme** [sphinx02/FireStarter#29]
Similar to the other issue regarding Magine, If you launch Tablo from Firestarter it will launch the default android ui rather than the ui made for tv that gets launched when you open it from amazon fire home or if you option click and launch program from firestarter. I made a thread about it on tablo's forum here:

https://community.tablotv.com/t/issue-with-2-2-8-and-firetv-2-with-firestarter/5097

**Comment by sphinx02** [comment]
Hi,
this is a problem of FireStarter. Newer Apps which are using the Leanback-Lib are handled different! I will fix this in the next release!

**Comment by riseagainstme** [comment]
thats wonderful news. I really appreciate your hard work, firestarter is an absolute must for firetv in my book.

**Comment by riseagainstme** [comment]
Just wanted to say, tried out 3.2.2 and it opened tablo perfectly. Thanks!
