### ISSUE TITLE
FireTV Stick - Kodi crash also crashes FireStarter

### ISSUE THREAD

**Issue by emsol** [sphinx02/FireStarter#3]
I'm not sure if I need to include any logs or anything, but on the FireTV Stick, if Kodi crashes the FireStarter launcher will also crash and you'll end up back on the amazon fire TV Home menu. the only way to get the FireStarter launcher back is to either force stop and relaunch it or reboot the device.

**Comment by sphinx02** [comment]
Hm, I had already crashes with Kodi where FireStarter was not affected. Can you explain in more detail what is the cause of Kodi crashing in your setup? The problem is, that I can only work on the problem if I can reproduce it and see what is causing this behaviour..

**Comment by emsol** [comment]
Hi Lukas
I'm am not sure what causes the crash. I can confirm that though that it doesn't happen often.If Kodi crashes on my fire TV box however, then FireStarter stays active, however if similar Kodi crash happens on fireTV stick then that's when FireStarter will also crash. It seems the issue is specific to fire stick and not fire box.
I will try to send you log next time Kodi crashes on the fire stick.
Also I have another suggestion. When in the 'settings' or 'updates' screen pressing the back button should return you to the Apps screen. Currently you must press left button in order to go back to the Apps screen. It would be better if the back button goes back to apps screen.
If you need any help with translations let me know, I have already spotted some places where the English can be improved.
Lastly do you take donations? I'd like to contribute.
Thanks,Adit.

Date: Fri, 24 Jul 2015 07:11:25 -0700

**Comment by sphinx02** [comment]
Hi Adit,
yes a log can be very helpful, would be great :) 
I will think about the back-button to return to app-overview.. Sounds interesting, perhaps as an option.. Will check this, thanks for the idea :). If you have any translation-corrections you can either make a pull-request here on GitHub or you can let me know here in the "issues".. I'm not a native english speaker, so I'm sure the english can be improved^^

You can find contribution links in the readme:
https://github.com/sphinx02/FireStarter#user-content-donation
or if readme do not show up directly:
https://github.com/sphinx02/FireStarter/blob/master/README.md#user-content-donation

Thank you very much for your feedback!
Best regards
Lukas

**Comment by emsol** [comment]
Sorry for the late reply, I have been mega busy.
I have sent 10euro donation - hope you have received it.
I will make a note of any language improvements and try to submit them via pull request; I have never done a pull request before though so I'm not 100% sure how to do that.
Thanks and keep up the good work!

Date: Fri, 24 Jul 2015 09:33:41 -0700

**Comment by sphinx02** [comment]
Not reproducible and very specific behaviour. Thanks anyway for the hint, I will keep an eye on it.
