### ISSUE TITLE
FireTV 2: Is USB Debugging required for Home-detection via ADB?

### ISSUE THREAD

**Issue by RoxKilly** [sphinx02/FireStarter#31]
On FireTV 2, have you guys had trouble with FireStarter v3.2.1 when you try to enable home button press detection via ADB? Actually this option is enabled by default I think, but I had to disable it (Open FireStarter > Settings > Home-detection via ADB).

Enabling this generates several errors unless I also enable USB Debugging in FireTV Settings > System > Developer Options. Problem is, enabling USB Debugging causes USB accessories (keyboard) to stop working so I'm in a catch 22 (ADB debugging is already enabled).

**Comment by sphinx02** [comment]
Hi @RoxKilly ,
you are right, if you want to use the home detection via ADB you have to enable ADB in the settings but enabling "ADB-Debugging" should suffice, "USB-Debugging" can stay disabled (checked it a second ago). Anyway, the alternative home detection without ADB is not that bad, you can also try this one.

Best regards
Lukas

**Comment by RoxKilly** [comment]
Thanks @sphinx02 .  I no longer observe the issue (Home-detection over ADB works even with USB Debugging off).  There was an issue though; if I can reproduce it in the future I will update this thread.
