### ISSUE TITLE
ADBFire Disabled after Installing version 3.2.2.2

### ISSUE THREAD

**Issue by ibm8086** [sphinx02/FireStarter#36]
After loading Firestarter, ADBFire 2.01 can no longer connect to my firetv. The IP address shows  but ADBFire reports it as OFFLINE. It appears that the ADBfire has been disabled. The firetv address appears with a .5555 as before.

**Comment by sphinx02** [comment]
This a known behaviour, see changlog of v3.0

And check the setting "**Home-Detection via ADB**":
_"If you are already on FireOS5 (Android v5.1), you have to make sure that no other device is connecting via ADB in parallel. If you want to use tools like adbFire, Amazon FireTV Utility App, Apps2Fire or similar, you should disable the ADB observation of the App and disable/enable ADB before you try to connect. If you want to use ADB observation again, make sure you disable/enable ADB before using it (Shortcut to ADB settings is below this Setting)."_

**Comment by ibm8086** [comment]
Thank you very much for this information. It did not work the first time. On my second attempt.I did the following steps in Firestarter.1) Disabled Background Observation2)Unchecked Home Detection via ADB.
The next step might not be relevant, but it worked for me. Removed power from the Firetv for at least 1 minute. Then went to the PC and tried to connect with ADBfire, to ensure I wasn't getting false messages.
Applied power to the Firetv and the ADBfire connected like there was no issue.
Thank you very much
Hubert 

```
On Tuesday, December 15, 2015 2:47 PM, Lukas Berger <notifications@github.com> wrote:
```

 This a known behaviour, see changlog of v3.0 
https://github.com/sphinx02/FireStarter/releases/tag/v3.0And check the setting "Home-Detection via ADB":
"If you are already on FireOS5 (Android v5.1), you have to make sure that no other device is connecting via ADB in parallel. If you want to use tools like adbFire, Amazon FireTV Utility App, Apps2Fire or similar, you should disable the ADB observation of FireStarter and disable/enable ADB before you try to connect. If you want to use ADB observation of FireStarter again, make sure you disable/enable ADB before using it (Shortcut to ADB settings is below this Setting)."—
