### ISSUE TITLE
FireStarter not launching on startup

### ISSUE THREAD

**Issue by InfernoK** [sphinx02/FireStarter#42]
Hi Guys,

Got an issue today. Installed FireStarter 3.2.2 via Adbfire onto my firestick (W87CUN model number). When i go to start up my firestick, the main amazon screen appears instead of the FireStarter app and when pressing the back and select button, it won't restart.

Any Suggestions?

**Comment by sphinx02** [comment]
You have to start FireStarter once before it starts to work!

If you are not familiar enough, please use my step by step guide:
https://github.com/sphinx02/FireStarter/wiki/Install-FireStarter-and-Kodi-%28only-FireTV-needed%29
