### ISSUE TITLE
Freetime extremely slow when trying to return to parent menu when Firestarter is running

### ISSUE THREAD

**Issue by pd-l2ork** [sphinx02/FireStarter#6]
I guess title says it all. Sometimes it takes several minutes before you even get a pin prompt and another couple of minutes to actually verify pin and exit the free time mode. Often times nothing happens and system simply hangs and if user presses home button during this wait they return back to the free time home screen. When firestarter is not running this process is near instantaneous as it should be. So, can anyone please confirm this?  If so, is there a way to disable Firestarter while in freetime mode to prevent this problem?

**Comment by sphinx02** [comment]
Hm, I have never used FreeTime.. Are you sure the problem is related to FireStarter? Are other Apps also slow when you are facing these issues with FreeTime or is it really only the combination FireStarter and FreeTime which makes problems?

**Comment by pd-l2ork** [comment]
Nothing else is affected The said problem seems to consistently crop up
when firestarter is running in the background. When I force close it, the
problem immediately goes away.

To test, create a freetime account (it is easy to erase later), and in
settings enable parental controls. Enter into freetime account and then try
to exit. It will take some time to get the pin/password prompt, and then
more to check the pin validity. Now, force close freetime and try the same.
If it takes too long to get the prompts, restart the AFT (hold select and
play buttons for 5 seconds), and you will reboot into freetime but will
have a bit of a Grace period nefore firestarter autostarts and typically
should be able to exit without any problems.

It may be this is affecting only my system, although, apart from a couple
of sideloaded humble bundle games, file browser, and firefox, it is
essentially a less than a year old, up to date vanilla system (no root).
Not sure if it makes any difference, but I also have two freetime accounts.

Best,

Ico

**Comment by sphinx02** [comment]
Never heard anything again about this very specific problem..

**Comment by pd-l2ork** [comment]
Did you actually get to test this on your own Fire TV? It is easy to set up a freetime account and erase it following the testing...

**Comment by necrevistonnezr** [comment]
I bet if you pay the developer, he can do all kinds of custom tests for you....
